services:
  postgresql:
    image: postgres:17.5-alpine3.22
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  graphy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080/tcp"
    container_name: graphy
    restart: unless-stopped
    environment:
      - ENV=production

volumes:
  postgresql-data: {}
