// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteNote struct {
	ID string `json:"id"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewNote struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Text        string `json:"text"`
}

type NewUser struct {
	Email    string `json:"email"`
	Fullname string `json:"fullname"`
	Password string `json:"password"`
}

type Note struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Text        string `json:"text"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdatedNote struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Text        *string `json:"text,omitempty"`
	Noteid      string  `json:"noteid"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Fullname string `json:"fullname"`
	Password string `json:"password"`
}
